-- Referencia: el adaptador ejecutable se encuentra en backend/src/sql.ts.
-- Dentro de la misma transacción que el comprobante de idempotencia:
-- UPDATE dbo.Orders
-- SET notes = @notes, updated_at = SYSUTCDATETIME()
-- OUTPUT inserted.version
-- WHERE id = @id AND version = @expected_version;
-- Si @@ROWCOUNT = 0: devolver 412 sin sobreescribir.
